export const TOPIC_CATEGORIES: Record<string, string[]> = {
  Identity:      ["Personal Info", "Personality", "Values", "Background"],
  Location:      ["Current City", "Neighborhoods", "Frequent Places"],
  Relationships: ["Family", "Friends", "Partner", "Colleagues"],
  Routine:       ["Morning", "Evening", "Weekly", "Rituals"],
  Work:          ["Current Role", "Skills", "Experience", "Goals"],
  Health:        ["Fitness", "Sleep", "Mental Health", "Medical"],
  Food:          ["Restaurants", "Home Cooking", "Preferences", "Dietary"],
  Entertainment: ["Music", "Film & TV", "Books", "Podcasts"],
  Style:         ["Purchases", "Preferences", "Wish List", "Brands"],
  Hobbies:       ["Active", "Creative", "Social", "Learning"],
  Travel:        ["Visited", "Wish List", "Travel Style"],
  Goals:         ["Short Term", "Long Term", "Completed"],
  Technology:    ["Purchases", "Preferences", "Wish List", "Brands"],
  Education:     ["Degrees & Certs", "Current Learning", "Interests"],
  Home:          ["Purchases", "Setup & Decor", "Wish List", "Neighborhood"],
  Childhood:     ["Where Grew Up", "Formative Experiences"],
  Community:     ["Causes", "Volunteering", "Local Groups"],
  Pets:          ["Animals", "Care", "Health"],
  Creativity:    ["Projects", "Tools", "Inspiration"],
  Finance:       ["Income", "Spending", "Savings", "Goals"],
  Beliefs:       ["Values", "Worldview"],
  Social:        ["Platforms", "Content", "Connections"],
  "Life Events": ["Recent", "Upcoming", "Impact"],
  Parenting:     ["Children", "School", "Activities", "Priorities"],
  Vehicle:       ["Current", "Shopping For", "Preferences", "Brands"],
  "Real Estate": ["Current Situation", "Plans", "Preferences"],
  Beauty:        ["Purchases", "Preferences", "Routine", "Wish List", "Brands"],
  Sports:        ["Activities", "Teams", "Equipment", "Events"],
  Events:        ["Attended", "Upcoming", "Wish List"],
  Gaming:        ["Platforms", "Games", "Wish List", "Preferences"],
  "Life Stage":  ["Current Stage", "Transitions", "Goals"],
}
